# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-25 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score_id',
        ),
    ]
